# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: EOS add-on
version: "1.1.1"
slug: eos
description: Energy Optimization System add-on
url: "https://github.com/Duetting/ha_eos_addon/tree/main/eos"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
  - config:rw
ports:
  8503/tcp: 8503
  8503/tcp: 8504
ports_description:
  8503/tcp: EOS fastapi server
  8504/tcp: EOS Dashboard
# options:
# schema:
backup_exclude:
  - /data/eos/cache
image: "ghcr.io/duetting/{arch}-addon-eos"
startup: services
